### ISSUE TITLE
Choose a final Bootstrap Theme

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#1]
Because we don't have anyone especially versed in frontend web on our team it makes sense to use the well known Bootstrap framework for our frontend. This lets any of us along with some help from Google/StackOverFlow make updates to the website while keeping it looking good.

Plain Bootstrap is really just a foundation and we should pick a theme so that our site looks good and at least semi original. For me the main requirements of a theme are that it looks good and that it has everything we need as is - I really want to avoid writing any custom/extra css for the site. The theme should also come with a solid example page and docs so that we can use it to its full potential (aka copy the frontend block from the example to our templates and add our content).

I am currently using the Stanley Theme from here: http://www.blacktie.co/2014/01/stanley-freelancer-theme/

Lets use this issue to decide on a final theme, either give a :+1: for Stanley or propose an alternative, here are some good sites for Bootstrap themes:

http://www.blacktie.co/
http://bootswatch.com/
http://bootstrapbay.com/

Some themes are not free but are quite inexpensive, I am happy to purchase any theme we decide on as a donation to Shogun.

This issue is a priority and is blocking several other issues from completion.

**Comment by kevinhughes27** [comment]
hey guys I am going to try and find some time to make some more progress on v2 of the shogun website and I want to revisit this issue. In the last couple of months I've gotten more competent with front end web dev and I've had some experience working with a layer of sass/css on top of bootstrap to make a site look good but not like vanilla bootstrap. All this is to say that I am going to drop the requirement that the theme needs to be good to go as is.

I am going to move forward with a combination of the free themes from blacktie.co and incorporate @lisitsyn's idea about using the Japanese angle with our branding. 

I am going to close this issue now and when I have something new to show I will open an issue for design feedback (although do remember I am not actually a designer just a more competent engineer :wink:)

**Comment by iglesias** [comment]
Sounds great, Kevin. Looking forward to see the new version. Success!

**Comment by karlnapf** [comment]
Looking forward to see your new skills in action!
