### ISSUE TITLE
Future of Shogun Planet

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#13]
do we actually want this? It takes a lot of control away from the content of the site. I think I would rather we cross posted blog entries manually if at all. What does everyone else think?

**Comment by kevinhughes27** [comment]
I'm gonna make the call to kill this. If anyone thinks otherwise we can discuss how to bring it back

**Comment by karlnapf** [comment]
I think the planet is nice, but it should be kept strictly seperate from the Shogun site and it should be clear that this is not our stuff, but just blogs of Shogun devs?

I always liked reading your posts there!
