### ISSUE TITLE
Notebook thumbnails

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#15]
Currently the notebook thumbnails are extracted by a script in this repository. I think we tried to automate too much here as there is a fair amount of issues with this approach:
- The images are all different sizes, resolutions and aspect ratios. This makes it hard to display them nicely
- The first image is not necessarily the best image in the notebook.

I'd like to see us address this manually and create a nice proper thumbnail for each notebook. This is related to #17

**Comment by karlnapf** [comment]
Done by @sperka
