### ISSUE TITLE
Notebook titles / abstracts

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#17]
the new website has a pop-up with the notebook name. Currently this is just extracted from the filename but it would be better if this was manual.

![image](https://cloud.githubusercontent.com/assets/1965489/7689827/3d75e9a2-fd7d-11e4-855f-b32df61764c6.png)

**Comment by karlnapf** [comment]
I like that!
Could we not change aspect ratios of the images?
H

**Comment by kevinhughes27** [comment]
see #15 I think we should take over manual control of the thumbnails too

**Comment by karlnapf** [comment]
Done by @sperka
