### ISSUE TITLE
Website Copy

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#18]
The copy in a few major locations should be reviewed and addressed:
- [x] Main page description
- [ ] Main page secondary tiles
- [ ] About page - what should even be on this page

main page:
http://shogun-web.herokuapp.com/

Main page description:
![image](https://cloud.githubusercontent.com/assets/1965489/7689869/8490d11c-fd7d-11e4-99a0-4729efe5d4ae.png)

Main page secondary tiles:
![image](https://cloud.githubusercontent.com/assets/1965489/7689880/92bc7e6c-fd7d-11e4-82c7-cb3a885b430c.png)

about page: 
http://shogun-web.herokuapp.com/about

**Comment by karlnapf** [comment]
We have an updated project description that is in the Readmes, we could re-use that I guess?

**Comment by karlnapf** [comment]
Nice draft!

I suggest to make some things visible on the *first page*:

 * Shogun is efficient ML in C++
 * Usable from *many target languages* under a *unified* interface
 * Link to Manual/example pages
 * Shogun is open-source

Everything else is secondary (in the sense that it should not be visible straight away) in my eyes

Some more comments:
 *  I really like the NEWS/git log/twitter feed in the lower part of the page
 * Fork me on github overlaps with contact
 * my reply is late. Is this the latest state?

**Comment by kevinhughes27** [comment]
> Fork me overlaps contact

are you on a really small screen?

> is this the latest state

yeah I haven't worked on this since making these issues

Yeah we could add a full width text area before the new section with some of those details to get people interested. Can someone writing something?

**Comment by karlnapf** [comment]
Done generally
