### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by iglesias** [shogun-toolbox/shogun-web2#20]
The red font at the bottom of the page on the dark background is hard to read.

**Comment by kevinhughes27** [comment]
Open to suggestions - I have been using colors form here: http://en.wikipedia.org/wiki/Traditional_colors_of_Japan to match or japan branding

**Comment by iglesias** [comment]
What about something that does not look so bright but still readable over the dark background? Maybe Dawn-color or Brewed mustard-brown from the list above?

**Comment by lisitsyn** [comment]
I think font can change the game here but no concrete suggestions.

**Comment by iglesias** [comment]
It reads lovely now!
