### ISSUE TITLE
Change order of main description and NEWS columns

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun-web2#24]
the main description could even go under "about" or so - if we have some bullet points we dont need that there. I think the news are quite important, they could even be before the feeds.

**Comment by kevinhughes27** [comment]
I can see how that looks. I thought it was nice to break it up a bit but it might work out

**Comment by karlnapf** [comment]
Hi

just looking at the website again. I think the main description (the updated one) should be under the 3 "main news" points.

**Comment by karlnapf** [comment]
Maybe even hide it completely from the main page, just put it on the "about" page.
Rather than this picture
Thoughts?

**Comment by kevinhughes27** [comment]
I will play with this along with #26 and see how it turns out
