### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun-web2#28]
- The ipython notebook images are badly scaled. Maybe reduce size?
- There are neither titles nor abstracts

I suggest to put the notebooks as a list of symbols-abstract, rather than in this grid. They can be on the lower part of the page.

On top should be a link to our new "cookbook", link is to come

**Comment by kevinhughes27** [comment]
dupe of #15 for the thumbnail images.

So you'd rather see a list instead of a grid with the abstracts?

**Comment by kevinhughes27** [comment]
It would be great if someone could help out with getting the scaled images of the notebooks

**Comment by karlnapf** [comment]
@iglesias do you want to take care of that?

**Comment by iglesias** [comment]
I am currently on holidays and barely accessing the computer. I will have some time in the new year :-)

**Comment by karlnapf** [comment]
Done by @sperka
