### ISSUE TITLE
Set up heroku-like deployment to shogun-toolbox.org

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun-web2#31]
It would be very convenient to have a git remote corresponding to ssh on the shogun-toolbox.org server. This way we just push changes through git when they are ready and then they are automatically online.

We can use something like that:
https://realpython.com/blog/python/kickstarting-flask-on-ubuntu-setup-and-deployment/

**Comment by karlnapf** [comment]
@lisitsyn wanna do this?

**Comment by karlnapf** [comment]
done
