### ISSUE TITLE
Link to github for release panel

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun-web2#35]
Currently, the left panel at the main website just renders a file called `RELEASE.md` from a submodule.

Can we make it render https://github.com/shogun-toolbox/shogun/releases/latest instead?
I mean only the release notes that are in there?

@sperka I have the feeling you can solve this in a few mins :) Would you mind?

**Comment by vigsterkr** [comment]
no need for this.... people can find the release page on github.
imo we should just add this badge maybe somewhere on the page:

<a href="https://github.com/shogun-toolbox/shogun/releases/latest"><img src="https://img.shields.io/github/release/shogun-toolbox/shogun.svg"></a>

**Comment by sperka** [comment]
I second the 'badge' opinion.
Btw, the RELEASE.md solution was created so that you update the RELEASE.md content at the time of release. To render the link you gave is stored in github-specific place, not in an independent repo

**Comment by karlnapf** [comment]
Done in c5ff2ba3b2dc1d22ff17ebfdd4e3313c36649527
