### ISSUE TITLE
Finalize copy on the home page

### ISSUE THREAD

**Issue by kevinhughes27** [shogun-toolbox/shogun-web2#4]
We should finalize the copy on the main page of the site. Presently I took the current about and then added the same 3 column section we had at some point, however some of this text is redundant although I like the the idea of having these 3 content blocks we just need to decide what goes in here:

![image](https://cloud.githubusercontent.com/assets/1965489/4435218/f5646f92-473a-11e4-862d-5921f1874c1a.png)

**Comment by kevinhughes27** [comment]
@karlnapf what should these 3 colums be right now?
Also can you take a look at the main description section - its pretty long and I wonder if it can be shorter
http://shogun-web.herokuapp.com/

**Comment by kevinhughes27** [comment]
I am going to close in favor of a new and more encompassing issue

**Comment by karlnapf** [comment]
I opened a few other issues around this, lets discuss there
